language: node_js
node_js:
- '4'
before_script:
- npm install grunt-cli -g
deploy:
  provider: npm
  email: labs@idealista.com
  api_key:
    secure: L46IVkEaKsKXlkr9mSLz5Yt397e6ymcD+ZLLWl2jmuJhS/Fx0Dl5UTv6BrI+axZMwMlxmcGrNstGIwTmBgtREbecJFxSXHgDx3cyU1vpTCWNA93QUoTkA8lqO5WSjNq6oK6FHizKjyLPDLkTEXRrbqR0H/Iv3pEFD/UPfHNtcoc1Rz/jTeJsx3kr2AZLvCcblmPFhx4r/YbR78Vl5G/B4w/iqmtuZOGfeJmIXVLEYy7gLAQboA50Poo7IGXOpJTih+mFsNJ8VrxnGXhn8ZF16hLDMGYGZUU676nqHq5fkePWvTCM7EED4tAY1J1onCjW0a7pc7+DE+MuBSQyEXHDXYCc69Y0qYIICnlxxA9NdSGib/NxyZpjIgaJP6V0Z1M09Z50N5gxWqp3nC1PBq1DtvtD/89mAeG4yXJ9dmdebx1+8ymqNFe3mjYTzqMIZOkPkoN3gdGpByi/ZkMFqNnk1I8Y9DK6Zui2iymu8x+f4ETstYYGkrjx+EwZkgZFujt79qNcn1XSXg+MHQDelxnCjHG2HLW35r+uRaCy2VxSBaslLd4bRjWkISJJxt5XkWDTFAvBg8l57baYU0Dz02lQEhsTXHeItBQ0PqXAE9zI2PT7FN/1fOOnN46EVGLjCPigkoHmQ+0C4WTcaRc6hN+mfbC6uAwMMs+pHMmNDs5DWCg=
  on:
    tags: true
    repo: idealista-tech/tlsh-js
